### PR TITLE
Switch to allocating all Rust objects in a fully managed heap

### PR DESCRIPTION
**Pull request by jacob-hughes**
The removed code in e4f4b3a was used to move Rust objects allocated from the unmanaged heap into the managed heap when they became owned by a `Gc`. This was introduced to support finalizer elision. 

There is a much simpler approach: to allocate everything in the managed heap, and assume that Rust-managed objects will always be rooted (and therefore never collected early). It was originally thought that this approach was infeasible because of the potential dangers of obfuscated pointers. However, after offline discussion with @ltratt, we've come to the conclusion that supporting obfuscated pointers is not worth the performance, ergonomic, and complexity trade-offs. Therefore, we now allocate all heap objects in the managed heap.

### CODE REVIEW

**Comment by ltratt** [comment]
Maybe a silly question but this seems to delete files that don't have much to do with the PR as-such?

**Comment by jacob-hughes** [comment]
I've just double checked and it's correct -- everything deleted was originally introduced to support runtime allocation switching. It was a lot of work!

**Comment by ltratt** [comment]
Blimey!

bors r+

**Comment by jacob-hughes** [comment]
bors try

**Comment by jacob-hughes** [comment]
This can be squashed now

**Comment by ltratt** [comment]
Please squash.

**Comment by jacob-hughes** [comment]
Squashed

**Pull request merged**
