### PR TITLE
Use custom hashbrown implementation

### PR DESCRIPTION
**Pull request by jacob-hughes**
This supports finalizer elision by implementing DropMethodFinalizerElidable on the backing table.

### CODE REVIEW

**Comment by jacob-hughes** [comment]
Oops. I've only jsut noticed that I didn't push my tests ([6d25f2c](https://github.com/softdevteam/alloy/pull/136/commits/6d25f2ce3b96ee0d1f7c1058009e3a358171501c)). Let me know if you're happy for me to squash.

**Comment by ltratt** [comment]
Please squash.

**Comment by jacob-hughes** [comment]
Squashed

**Comment by jacob-hughes** [comment]
Fixed here 9b2d28e04b6a9009711f674c847b9fd456e3f1e2

**Comment by ltratt** [comment]
Please squash.

**Comment by jacob-hughes** [comment]
Squashed

**Pull request merged**
