### PR TITLE
Move GC to standard library

### PR DESCRIPTION
**Pull request by jacob-hughes**
Currently, Alloy's GC lives in `library/alloc` and is then re-exported to `library/std` which is the convention for most heap allocated types. Unfortunately, this means that it is unable to use standard library items such as Mutexes and Channels as code in `library/alloc` must be `#[no_std]` compliant.

By moving `Gc` into `library/std` we can use standard library types for our off-thread finalisation implementation. This commit simply moves code around and does not make any functional changes to Alloy.

### CODE REVIEW

**Comment by ltratt** [comment]
bors ping

**Comment by vext01** [comment]
bors ping

**Comment by ltratt** [comment]
@jacob-hughes Can I check that you've run the whole CI test suite for this?

**Comment by jacob-hughes** [comment]
Yeah, this has now passed with `/usr/bin/time -v python3 x.py test --stage 2 --config .buildbot.config.toml --exclude rustdoc-json --exclude debuginfo`. Bit slow on my local machine!

**Comment by ltratt** [comment]
Oops I missed this message -- sorry!

**Pull request merged**
