### PR TITLE
Test yksom and grmtools as part of CI

### PR DESCRIPTION
**Pull request by jacob-hughes**

### CODE REVIEW

**Comment by jacob-hughes** [comment]
This is a tricky one because it’s hard to attach gdb at the place where this fails. Working on it!

**Comment by jacob-hughes** [comment]
This has been fixed [here](https://github.com/softdevteam/bdwgc/pull/9) and can be merged once it lands.

**Comment by jacob-hughes** [comment]
Fixed here (f0d2059c300f28402f144a31fbebe6db89f75069), if you're happy I'll squash.

**Comment by ltratt** [comment]
Please squash.

**Comment by jacob-hughes** [comment]
Squashed

**Pull request merged**
